"""Public surface of the Asclepius config package.

Everything callers used to import from ``asclepius.config`` (the old flat
module) is re-exported here so ``from asclepius.config import AppConfig,
get_config, LlmProviderEntry, ...`` keeps working.
"""

from .models import (
    DEFAULT_SECRET_PLACEHOLDER,
    AppConfig,
    AuthConfig,
    BackupConfig,
    CredentialEntry,
    DatabaseConfig,
    GeneralLlmConfig,
    LlmConfig,
    LlmProviderEntry,
    OcrConfig,
    OcrProviderEntry,
    OidcConfig,
    PipelineConfig,
    ServerConfig,
    VaultConfig,
    VisionConfig,
    VisionLlmProviderEntry,
)
from .resolver import (
    _apply_env_claude_key,
    _apply_env_ollama_url,
    _BASELESS_CREDENTIAL_TYPES,
    _ensure_credential,
    _first_enabled_llm,
    _LEGACY_LLM_KEYS,
    _migrate_credentials,
    _migrate_legacy_llm_yaml,
    _migrate_vision_extraction_ocr_yaml,
    _new_credential_id,
    _normalise_base_url,
    _persist_yaml,
    _validate_production_config,
    generate_secret_key,
    get_active_llm_provider_config,
    get_active_ocr_provider_config,
    get_active_vision_provider_config,
    get_config,
    load_config,
    resolve_credential,
)

__all__ = [
    "DEFAULT_SECRET_PLACEHOLDER",
    "AppConfig",
    "AuthConfig",
    "BackupConfig",
    "CredentialEntry",
    "DatabaseConfig",
    "GeneralLlmConfig",
    "LlmConfig",
    "LlmProviderEntry",
    "OcrConfig",
    "OcrProviderEntry",
    "OidcConfig",
    "PipelineConfig",
    "ServerConfig",
    "VaultConfig",
    "VisionConfig",
    "VisionLlmProviderEntry",
    "generate_secret_key",
    "get_active_llm_provider_config",
    "get_active_ocr_provider_config",
    "get_active_vision_provider_config",
    "get_config",
    "load_config",
    "resolve_credential",
]
